export interface GalleryItem {
  src: string;
  alt?: string;
  caption?: string;
  subSlides?: GalleryItem[];
  isVideo?: boolean;
}

export interface SectionDetails {
  client: string;
  industry: string;
  role: string;
  year: string;
  deliverables: string;
  tools: string;
}

export interface SectionData {
  title: string;
  username: string;
  bio: string;
  avatarImage: string;
  avatarText: string;
  avatarBg: string;
  posts: GalleryItem[];
  details: SectionDetails;
  overview: string;
  challenge: string;
}

export const desainLainItems: GalleryItem[] = [
  { src: "/portfolio/backdrop-fa.jpg", alt: "Backdrop Forum Anak", caption: "Backdrop Forum Anak" },
  { src: "/portfolio/billboard-uksw.jpg", alt: "Billboard UKSW", caption: "Billboard UKSW" },
  { src: "/portfolio/spanduk-pelkatpa.jpg", alt: "Spanduk Pelkat PA", caption: "Spanduk Pelkat PA" },
  { src: "/portfolio/campaign.jpg", alt: "Campaign Design", caption: "Campaign Design" },
];

export const liveStreamItems: GalleryItem[] = [
  { src: "/portfolio/live-anya.mp4", alt: "Anya Zona Layer", caption: "Anya Zona Layer Live Stream Design", isVideo: true },
  { src: "/portfolio/live-ez.mp4", alt: "EZ Squad", caption: "EZ Squad Live Stream Design", isVideo: true },
  { src: "/portfolio/live-raka.mp4", alt: "Raka Trabas", caption: "Raka Trabas Live Stream Design", isVideo: true },
  { src: "/portfolio/live-reno.mp4", alt: "Sinyal Ordal", caption: "Sinyal Ordal Live Stream Design", isVideo: true },
];

export const liveProfiles = [
  { title: "Anya Zona Layer", username: "anya", avatarImage: "/portfolio/anya.jpg", avatarText: "A", avatarBg: "from-pink-400 to-rose-500" },
  { title: "EZ Squad", username: "ezsquad", avatarImage: "/portfolio/ez.jpg", avatarText: "EZ", avatarBg: "from-purple-400 to-violet-600" },
  { title: "Raka Trabas", username: "rakatrabas", avatarImage: "/portfolio/raka.jpg", avatarText: "RT", avatarBg: "from-orange-400 to-red-500" },
  { title: "Sinyal Ordal", username: "sinyalordal", avatarImage: "/portfolio/sinyalordal.jpg", avatarText: "SO", avatarBg: "from-blue-400 to-cyan-500" },
];

export const defaultThumbnailGrid: GalleryItem[] = Array.from({ length: 9 }, (_, index) => {
  const num = index + 1;
  return {
    src: `/portfolio/thumbnail-${num}.jpg`,
    alt: `Thumbnail ${num}`,
    caption: `Thumbnail ${num}`,
  };
});

export const socialSections: SectionData[] = [
  {
    title: "Pelkat PA GPIB Immanuel Pekanbaru",
    username: "pelkatpa.pku",
    bio: "Ruang ceria anak-anak kreatif & penuh kasih Tuhan 🙏✨ GPIB Immanuel Pekanbaru.",
    avatarImage: "/portfolio/pa-logo.jpg",
    avatarText: "P",
    avatarBg: "from-blue-500 to-indigo-400",
    posts: [
      { src: "/portfolio/pa-1.png"},
      { src: "/portfolio/pa-2.jpg"},
      { src: "/portfolio/pa-3.jpg"},
      { src: "/portfolio/pa-4.jpg"},
      { src: "/portfolio/pa-5.jpg"},
      { src: "/portfolio/pa-6.jpg"},
    ],
    details: {
      client: "Pelkat PA GPIB Immanuel Pekanbaru",
      industry: "Community & Ministry",
      role: "Visual Designer",
      year: "2024",
      deliverables: "Event Assets, Social Media Story Templates",
      tools: "Adobe Illustrator, Canva",
    },
    overview: "Created joyful and engaging visual content for children's ministry events and daily spiritual communication. The designs were developed to feel vibrant, warm, and approachable while maintaining a clear and consistent visual identity.",
    challenge: "The main challenge was balancing a playful, child-friendly aesthetic with the established branding and visual guidelines of the church.",
  },
  {
    title: "UKSW",
    username: "uksw_salatiga",
    bio: "Official visual feed for UKSW Salatiga 🎓 Shaping futures through creative campus stories.",
    avatarImage: "/portfolio/uksw-logo.jpg",
    avatarText: "U",
    avatarBg: "from-pink-500 to-rose-400",
    posts: [
      { src: "/portfolio/uksw-1.jpg", alt: "UKSW Mendunia", caption: "UKSW Mendunia" },
      {
        src: "/portfolio/uksw-2.jpg",
        alt: "Kampus Tour",
        caption: "Kampus Tour",
        subSlides: [
          { src: "/portfolio/uksw-2.jpg"},
          { src: "/portfolio/uksw-2a.jpg"},
          { src: "/portfolio/uksw-2b.jpg"},
          { src: "/portfolio/uksw-2c.jpg"},
        ],
      },
      { src: "/portfolio/uksw-3.jpg", alt: "PMB 2026", caption: "Rumah Noto" },
      { src: "/portfolio/uksw-4.jpg", alt: "Akreditasi Unggul", caption: "Passover Poster" },
      { src: "/portfolio/uksw-5.jpg", alt: "UKSW Menyapa", caption: "Passover Poster" },
      { src: "/portfolio/uksw-6.jpg", alt: "Creative Minority", caption: "Quotes" },
      {
        src: "/portfolio/uksw-7.jpg",
        alt: "Campus Life",
        caption: "Campus Life",
        subSlides: [
          { src: "/portfolio/uksw-7.jpg"},
          { src: "/portfolio/uksw-7a.jpg"},
          { src: "/portfolio/uksw-7b.jpg"},
          { src: "/portfolio/uksw-7c.jpg"},
        ],
      },
      { src: "/portfolio/uksw-8.jpg", alt: "Research & Innovation", caption: "Research & Innovation" },
      { src: "/portfolio/uksw-9.jpg", alt: "Graduation Moment", caption: "Graduation Moment" },
    ],
    details: {
      client: "UKSW Salatiga",
      industry: "Education",
      role: "Visual Design Intern",
      year: "2022",
      deliverables: "Social Media Content, Thumbnails, Photography",
      tools: "Adobe Photoshop, Adobe Illustrator",
    },
    overview: "Created engaging visual content for the university's social media platforms, including promotional posts, video thumbnails, and photography to support various campus activities and communications.",
    challenge: "Creating visually engaging and consistent content for different campus communications while adapting to a variety of formats, audiences, and creative needs.",
  },
  {
    title: "Jendela Finansial",
    username: "jendelafinansial",
    bio: "Smart financial tips & wealth education made simple 💡 Grow your future with us.",
    avatarImage: "/portfolio/jendela-finansial-logo.jpg",
    avatarText: "JF",
    avatarBg: "from-emerald-500 to-teal-400",
    posts: [
      {
        src: "/portfolio/jendela-1.jpg",
        alt: "jendela-1",
        caption: "jendela-1",
        subSlides: [
          { src: "/portfolio/jendela-1.jpg"},
          { src: "/portfolio/jendela-1a.jpg"},
          { src: "/portfolio/jendela-1b.jpg"},
          { src: "/portfolio/jendela-1c.jpg"},
          { src: "/portfolio/jendela-1d.jpg"},
          { src: "/portfolio/jendela-1e.jpg"},
        ],
      },
      {
        src: "/portfolio/jendela-2.jpg",
        alt: "jendela-2",
        caption: "jendela-2",
        subSlides: [
          { src: "/portfolio/jendela-2.jpg"},
          { src: "/portfolio/jendela-2a.jpg"},
          { src: "/portfolio/jendela-2b.jpg"},
          { src: "/portfolio/jendela-2c.jpg"},
          { src: "/portfolio/jendela-2d.jpg"},
        ],
      },
      {
        src: "/portfolio/jendela-3.jpg",
        alt: "jendela-3",
        caption: "jendela-3",
        subSlides: [
          { src: "/portfolio/jendela-3.jpg"},
          { src: "/portfolio/jendela-3a.jpg"},
          { src: "/portfolio/jendela-3b.jpg"},
          { src: "/portfolio/jendela-3c.jpg"},
          { src: "/portfolio/jendela-3d.jpg"},
          { src: "/portfolio/jendela-3e.jpg"},
        ],
      },
      {
        src: "/portfolio/jendela-4.jpg",
        alt: "jendela-4",
        caption: "jendela-4",
        subSlides: [
          { src: "/portfolio/jendela-4.jpg"},
          { src: "/portfolio/jendela-4a.jpg"},
          { src: "/portfolio/jendela-4b.jpg"},
          { src: "/portfolio/jendela-4c.jpg"},
          { src: "/portfolio/jendela-4d.jpg"},
          { src: "/portfolio/jendela-4e.jpg"},
          { src: "/portfolio/jendela-4f.jpg"},
          { src: "/portfolio/jendela-4g.jpg"},
          { src: "/portfolio/jendela-4h.jpg", alt: "jendela-4h", caption: "jendela-4h" },
        ],
      },
      { src: "/portfolio/jendela-5.jpg"},
      {
        src: "/portfolio/jendela-6.jpg",
        alt: "jendela-6",
        caption: "jendela-6",
        subSlides: [
          { src: "/portfolio/jendela-6.jpg"},
          { src: "/portfolio/jendela-6a.jpg"},
          { src: "/portfolio/jendela-6b.jpg"},
          { src: "/portfolio/jendela-6c.jpg"},
          { src: "/portfolio/jendela-6d.jpg"},
          { src: "/portfolio/jendela-6e.jpg"},
          { src: "/portfolio/jendela-6f.jpg"},
        ],
      },
    ],
    details: {
      client: "Jendela Finansial",
      industry: "Financial Education",
      role: "Lead Visual Designer",
      year: "2024",
      deliverables: "Social Media Content, Character Design, Branding Assets, Educational Campaigns",
      tools: "Adobe Photoshop, Adobe Illustrator",
    },
    overview: "Developed visual content and branding assets for a financial education platform focused on helping Gen Z become more financially aware. The work included creating social media content, original character designs, and engaging visuals for financial challenges, news, and educational content.",
    challenge: "Making financial topics approachable and engaging for Gen Z while building a distinctive visual identity that could communicate educational content, financial news, and interactive challenges in a clear, relatable, and visually appealing way.",
  },
  {
    title: "Consistrade",
    username: "consistrade",
    bio: "Professional corporate and trading brand identity design 📈 Global trade made seamless.",
    avatarImage: "/portfolio/consistrade-logo.png",
    avatarText: "C",
    avatarBg: "from-purple-500 to-pink-500",
    posts: [
      { src: "/portfolio/consistrade-1.png"},
      { src: "/portfolio/consistrade-2.png"},
      { src: "/portfolio/consistrade-3.png"},
      { src: "/portfolio/consistrade-4.png"},
      { src: "/portfolio/consistrade-5.png"},
      { src: "/portfolio/consistrade-6.png"},
      { src: "/portfolio/consistrade-7.png"},
      { src: "/portfolio/consistrade-8.png"},
      { src: "/portfolio/consistrade-9.png"},
    ],
    details: {
      client: "Consistrade",
      industry: "Financial & Trading Education",
      role: "Graphic Designer & Brand Designer",
      year: "2025",
      deliverables: "Brand Identity, Social Media Content, Character Design, Digital Learning Assets",
      tools: "Adobe Photoshop, Adobe Illustrator, Canva",
    },
    overview: "Developed visual and branding assets for Consistrade, a financial education platform focused on helping traders—from beginners to professionals—learn and grow consistently. The work included building a cohesive brand identity, creating character designs, and developing engaging visual assets for digital products, trading modules, educational classes, and community-based content.",
    challenge: "Creating a visual identity that feels approachable for beginner traders while maintaining credibility and relevance for more experienced audiences. The challenge was to transform complex trading and financial concepts into clear, engaging, and visually consistent content that supports learning, community engagement, and Consistrade's digital education ecosystem.",
  },
];

export const brandSections: SectionData[] = [
  {
    title: "Jendela Finansial",
    username: "jendelafinansial",
    bio: "Smart financial tips & wealth education brand identity 💡",
    avatarImage: "/portfolio/jendela-finansial.jpg",
    avatarText: "JF",
    avatarBg: "from-emerald-500 to-teal-400",
    posts: [{ src: "/portfolio/jendela-finansial.jpg", alt: "Jendela Finansial Logo", caption: "Jendela Finansial Logo" }],
    details: {
      client: "Jendela Finansial",
      industry: "Financial Education",
      role: "Lead Visual Designer",
      year: "2024",
      deliverables: "Social Media Content, Character Design, Branding Assets, Educational Campaigns",
      tools: "Adobe Photoshop, Adobe Illustrator",
    },
    overview: "Developed visual content and branding assets for a financial education platform focused on helping Gen Z become more financially aware. The work included creating social media content, original character designs, and engaging visuals for financial challenges, news, and educational content.",
    challenge: "Making financial topics approachable and engaging for Gen Z while building a distinctive visual identity that could communicate educational content, financial news, and interactive challenges in a clear, relatable, and visually appealing way.",
  },
  {
    title: "Pelkat PA GPIB Immanuel Pekanbaru",
    username: "gpib_immanuel_pku",
    bio: "Official church branding and visual identity system 🙏🕊️",
    avatarImage: "/portfolio/pelkatpa.jpg",
    avatarText: "G",
    avatarBg: "from-amber-500 to-orange-400",
    posts: [{ src: "/portfolio/pelkatpa.jpg", alt: "GPIB Immanuel Pekanbaru", caption: "GPIB Immanuel Pekanbaru" }],
    details: {
      client: "GPIB Immanuel Pekanbaru",
      industry: "Religious Organization",
      role: "Lead Brand Designer",
      year: "2024",
      deliverables: "Visual Identity, Stationery",
      tools: "Illustrator, Figma",
    },
    overview: "Establishing a dignified and welcoming brand presence for the congregation.",
    challenge: "Reflecting traditional ecclesiastical values through modern, clean graphic standards.",
  },
  {
    title: "GPIB Immanuel Pekanbaru",
    username: "gpibimmanuelpku",
    bio: "Official church branding and visual identity system 🙏🕊️",
    avatarImage: "/portfolio/gpib-sinode.jpg",
    avatarText: "G",
    avatarBg: "from-amber-500 to-orange-400",
    posts: [{ src: "/portfolio/gpib-thumb.jpg", alt: "GPIB Immanuel Pekanbaru", caption: "GPIB Immanuel Pekanbaru" }],
    details: {
      client: "GPIB Immanuel Pekanbaru",
      industry: "Religious Organization",
      role: "Lead Brand Designer",
      year: "2024",
      deliverables: "Visual Identity, Stationery",
      tools: "Illustrator, Figma",
    },
    overview: "Establishing a dignified and welcoming brand presence for the congregation.",
    challenge: "Reflecting traditional ecclesiastical values through modern, clean graphic standards.",
  },
  {
    title: "Consistrade",
    username: "consistrade",
    bio: "Professional corporate and trading brand identity design 📈",
    avatarImage: "/portfolio/consistrade-thumb.jpg",
    avatarText: "C",
    avatarBg: "from-purple-500 to-pink-500",
    posts: [{ src: "/portfolio/consistrade-thumb.jpg", alt: "Consistrade", caption: "Consistrade" }],
    details: {
      client: "Consistrade",
      industry: "Financial & Trading Education",
      role: "Graphic Designer & Brand Designer",
      year: "2025",
      deliverables: "Brand Identity, Social Media Content, Character Design, Digital Learning Assets",
      tools: "Adobe Photoshop, Adobe Illustrator, Canva",
    },
    overview: "Developed visual and branding assets for Consistrade, a financial education platform focused on helping traders—from beginners to professionals—learn and grow consistently. The work included building a cohesive brand identity, creating character designs, and developing engaging visual assets for digital products, trading modules, educational classes, and community-based content.",
    challenge: "Creating a visual identity that feels approachable for beginner traders while maintaining credibility and relevance for more experienced audiences. The challenge was to transform complex trading and financial concepts into clear, engaging, and visually consistent content that supports learning, community engagement, and Consistrade's digital education ecosystem.",
  },
  {
    title: "HUT 63 Pelkat PA GPIB",
    username: "pelkatpa.pku",
    bio: "Winning logo design for the 63rd Anniversary of Pelkat PA GPIB 🏆",
    avatarImage: "/portfolio/hut63.jpg",
    avatarText: "PA",
    avatarBg: "from-rose-500 to-pink-500",
    posts: [{ src: "/portfolio/hut63.jpg", alt: "PA Logo HUT 63", caption: "PA Logo HUT 63" }],
    details: {
      client: "Dewan Pelayanan Anak",
      industry: "Ministry",
      role: "Graphic Designer",
      year: "2023",
      deliverables: "Logo Competition Entry",
      tools: "Illustrator",
    },
    overview: "Winning design for the 63rd Pelkat PA GPIB Anniversary logo competition.",
    challenge: "Capturing the spirit of 63 years of service within a concise, iconic mark.",
  },
  {
    title: "HUT 67 Pelkat PA GPIB",
    username: "pelkatpa.pku",
    bio: "Official visual identity for the 67th Pelkat PA GPIB Anniversary 🕊️",
    avatarImage: "/portfolio/hut67.jpg",
    avatarText: "PA",
    avatarBg: "from-blue-500 to-indigo-500",
    posts: [{ src: "/portfolio/hut67.jpg", alt: "Logo HUT Pelkat PA ke-67", caption: "Logo HUT Pelkat PA ke-67" }],
    details: {
      client: "Logo HUT Pelkat PA ke-67",
      industry: "Ministry",
      role: "Lead Brand Designer",
      year: "2024",
      deliverables: "Anniversary Logo",
      tools: "Illustrator, Photoshop",
    },
    overview: "Developing a celebratory and meaningful identity for the 67th anniversary.",
    challenge: "Creating a distinct mark that aligns with church branding while signifying longevity.",
  },
  {
    title: "Soleste",
    username: "soleste_official",
    bio: "Elegance and modern lifestyle brand identity design ✨",
    avatarImage: "/portfolio/soleste.jpg",
    avatarText: "S",
    avatarBg: "from-amber-400 to-yellow-600",
    posts: [{ src: "/portfolio/soleste.jpg", alt: "Soleste Brand", caption: "Soleste Brand Identity" }],
    details: {
      client: "Soleste",
      industry: "Lifestyle & Fashion",
      role: "Lead Brand Designer",
      year: "2024",
      deliverables: "Brand Strategy, Visual Identity",
      tools: "Illustrator, Figma",
    },
    overview: "Crafting a refined, luxury-feeling brand identity for modern lifestyle products.",
    challenge: "Encapsulating sophistication and minimalism while keeping the brand warm and accessible.",
  },
];

export const logoSections: SectionData[] = [
  {
    title: "HUT 63 Pelkat PA GPIB",
    username: "pelkatpa.pku",
    bio: "Winning anniversary emblem for Pelkat PA GPIB 🏆",
    avatarImage: "/portfolio/hut63.jpg",
    avatarText: "PA",
    avatarBg: "from-rose-500 to-pink-500",
    posts: [{ src: "/portfolio/hut63.jpg", alt: "PA Logo HUT 63", caption: "HUT 63 Pelkat PA Logo" }],
    details: {
      client: "Dewan Pelayanan Anak",
      industry: "Religious & Youth",
      role: "Logo Designer",
      year: "2023",
      deliverables: "Competition Winner Emblem",
      tools: "Illustrator",
    },
    overview: "Celebratory 63rd anniversary logo winning entry capturing faith and joy.",
    challenge: "Merging numeric elements with church motifs into a unified circular mark.",
  },
  {
    title: "HUT 67 Pelkat PA GPIB",
    username: "pelkatpa.pku",
    bio: "Official 67th anniversary visual mark 🕊️",
    avatarImage: "/portfolio/hut67.jpg",
    avatarText: "PA",
    avatarBg: "from-blue-500 to-indigo-500",
    posts: [{ src: "/portfolio/hut67.jpg", alt: "Logo HUT Pelkat PA ke-67", caption: "HUT 67 Pelkat PA Logo" }],
    details: {
      client: "Pelkat PA GPIB",
      industry: "Religious & Youth",
      role: "Logo Designer",
      year: "2024",
      deliverables: "Official Anniversary Logo",
      tools: "Illustrator",
    },
    overview: "Modern anniversary identity commemorating 67 years of service and spiritual growth.",
    challenge: "Creating a fresh visual theme while respecting long-standing organizational identity.",
  },
  {
    title: "GPIB Immanuel Pekanbaru",
    username: "gpib_immanuel_pku",
    bio: "Official church emblem and logo mark 🙏🕊️",
    avatarImage: "/portfolio/gpib.jpg",
    avatarText: "G",
    avatarBg: "from-amber-500 to-orange-400",
    posts: [{ src: "/portfolio/gpib.jpg", alt: "GPIB Immanuel Pekanbaru Logo", caption: "GPIB Immanuel Pekanbaru Logo Design" }],
    details: {
      client: "GPIB Immanuel Pekanbaru",
      industry: "Religious Organization",
      role: "Logo Designer",
      year: "2024",
      deliverables: "Church Logo & Visual Mark",
      tools: "Illustrator",
    },
    overview: "Establishing a dignified and welcoming brand presence for the congregation.",
    challenge: "Reflecting traditional ecclesiastical values through modern, clean graphic standards.",
  },
  {
    title: "Joko Tuo",
    username: "jokotuo_heritage",
    bio: "Traditional heritage & authentic culinary mark 🌿",
    avatarImage: "/portfolio/jokotuo.jpg",
    avatarText: "JT",
    avatarBg: "from-emerald-700 to-green-600",
    posts: [{ src: "/portfolio/jokotuo.jpg", alt: "Joko Tuo Logo", caption: "Joko Tuo Logo Design" }],
    details: {
      client: "Joko Tuo",
      industry: "Culinary & Heritage",
      role: "Logo Designer",
      year: "2024",
      deliverables: "Vintage Monogram & Seal",
      tools: "Illustrator, Photoshop",
    },
    overview: "A rich, heritage-inspired logo mark reflecting authentic cultural recipes and tradition.",
    challenge: "Infusing traditional retro artwork while keeping the logo modern and scalable.",
  },
  {
    title: "Consistrade",
    username: "consistrade",
    bio: "Sleek & authoritative corporate trading mark 📈",
    avatarImage: "/portfolio/consistrade.jpg",
    avatarText: "C",
    avatarBg: "from-indigo-600 to-blue-500",
    posts: [{ src: "/portfolio/consistrade.jpg", alt: "Consistrade Logo", caption: "Consistrade Logo Design" }],
    details: {
      client: "Consistrade",
      industry: "Financial & Trading Education",
      role: "Graphic Designer & Brand Designer",
      year: "2025",
      deliverables: "Brand Identity, Social Media Content, Character Design, Digital Learning Assets",
      tools: "Adobe Photoshop, Adobe Illustrator, Canva",
    },
    overview: "Developed visual and branding assets for Consistrade, a financial education platform focused on helping traders—from beginners to professionals—learn and grow consistently. The work included building a cohesive brand identity, creating character designs, and developing engaging visual assets for digital products, trading modules, educational classes, and community-based content.",
    challenge: "Creating a visual identity that feels approachable for beginner traders while maintaining credibility and relevance for more experienced audiences. The challenge was to transform complex trading and financial concepts into clear, engaging, and visually consistent content that supports learning, community engagement, and Consistrade's digital education ecosystem.",
  },
  {
    title: "Minci",
    username: "minci_brand",
    bio: "Playful & friendly mascot-driven brand logo 🐱",
    avatarImage: "/portfolio/minci.jpg",
    avatarText: "M",
    avatarBg: "from-pink-400 to-rose-400",
    posts: [{ src: "/portfolio/minci.jpg", alt: "Minci Logo", caption: "Minci Logo Design" }],
    details: {
      client: "Minci",
      industry: "Consumer Goods",
      role: "Logo Designer",
      year: "2024",
      deliverables: "Character Logo & Packaging Badge",
      tools: "Illustrator",
    },
    overview: "Warm and inviting character-based logo design built for high brand recall.",
    challenge: "Balancing cute mascot elements with scalable graphic typography.",
  },
  {
    title: "Nona Kirana",
    username: "nonakirana",
    bio: "Charming & feminine aesthetic visual identity 🌸",
    avatarImage: "/portfolio/kirana.jpg",
    avatarText: "NK",
    avatarBg: "from-pink-300 to-purple-400",
    posts: [{ src: "/portfolio/kirana.jpg", alt: "Nona Kirana Logo", caption: "Nona Kirana Logo Design" }],
    details: {
      client: "Nona Kirana",
      industry: "Beauty & Beauty Care",
      role: "Logo Designer",
      year: "2024",
      deliverables: "Wordmark & Monogram",
      tools: "Illustrator, Font Self",
    },
    overview: "Elegant typographic and monogram design crafted for personal branding and beauty.",
    challenge: "Designing delicate line work that maintains clarity across small digital icons.",
  },
  {
    title: "Sinyal Ordal",
    username: "sinyalordal",
    bio: "Tech & insider signals community mark 📡",
    avatarImage: "/portfolio/sinyalordal.jpg",
    avatarText: "SO",
    avatarBg: "from-cyan-500 to-blue-600",
    posts: [{ src: "/portfolio/sinyalordal.jpg", alt: "Sinyal Ordal Logo", caption: "Sinyal Ordal Logo Design" }],
    details: {
      client: "Sinyal Ordal",
      industry: "Technology & Community",
      role: "Logo Designer",
      year: "2024",
      deliverables: "Digital Logo Suite",
      tools: "Illustrator, Figma",
    },
    overview: "A sharp, futuristic logo design symbolising signal flow and exclusive networking.",
    challenge: "Crafting an abstract signal icon that feels both tech-forward and trustworthy.",
  },
  {
    title: "Soleste",
    username: "soleste_official",
    bio: "Modern & elegant lifestyle brand mark ✨",
    avatarImage: "/portfolio/soleste.jpg",
    avatarText: "S",
    avatarBg: "from-amber-400 to-yellow-600",
    posts: [{ src: "/portfolio/soleste.jpg", alt: "Soleste Logo", caption: "Soleste Logo Design" }],
    details: {
      client: "Soleste",
      industry: "Lifestyle & Fashion",
      role: "Logo Designer",
      year: "2024",
      deliverables: "Logo Mark, Identity System",
      tools: "Illustrator, Vector",
    },
    overview: "A refined and luxury-feeling brand mark tailored for modern lifestyle products.",
    challenge: "Creating a simple yet memorable emblem that conveys elegance and durability.",
  },
  {
    title: "Pivot Point by Mark Liem",
    username: "pivotpoint_markliem",
    bio: "Executive coaching & strategic consulting logo 🎯",
    avatarImage: "/portfolio/pivot.jpg",
    avatarText: "PP",
    avatarBg: "from-slate-700 to-zinc-900",
    posts: [{ src: "/portfolio/pivot.jpg", alt: "Pivot Point Logo", caption: "Pivot Point Logo Design" }],
    details: {
      client: "Mark Liem",
      industry: "Consulting & Executive Coaching",
      role: "Logo Designer",
      year: "2024",
      deliverables: "Personal Branding Logo",
      tools: "Illustrator, Figma",
    },
    overview: "Minimalist monogram emblem designed for high-level personal executive branding.",
    challenge: "Distilling strategic transformation and direction into a sleek geometric monogram.",
  },
  {
    title: "Raka Trabas",
    username: "rakatrabas",
    bio: "Dynamic & energetic adventure community logo 🚵‍♂️",
    avatarImage: "/portfolio/raka.jpg",
    avatarText: "RT",
    avatarBg: "from-orange-500 to-red-500",
    posts: [{ src: "/portfolio/raka.jpg", alt: "Raka Trabas Logo", caption: "Raka Trabas Logo Design" }],
    details: {
      client: "Raka Trabas",
      industry: "Outdoor & Sports",
      role: "Logo Designer",
      year: "2024",
      deliverables: "Community Logo, Apparel Badge",
      tools: "Illustrator, Photoshop",
    },
    overview: "Bold and high-energy logo mark created for off-road & adventure sports enthusiasts.",
    challenge: "Blending ruggedness with clean, modern vector lines for print on merchandise.",
  },
];