export interface GalleryItem {
  src: string;
  alt?: string;
  caption?: string;
  subSlides?: GalleryItem[];
  isVideo?: boolean;
}

export interface SectionDetails {
  client: string;
  industry: string;
  role: string;
  year: string;
  deliverables: string;
  tools: string;
}

export interface SectionData {
  title: string;
  username: string;
  bio: string;
  avatarImage: string;
  avatarText: string;
  avatarBg: string;
  posts: GalleryItem[];
  details: SectionDetails;
  overview: string;
  challenge: string;
}

export const desainLainItems: GalleryItem[] = [
  { src: "/portfolio/backdrop-fa.jpg", alt: "Backdrop Forum Anak", caption: "Backdrop Forum Anak" },
  { src: "/portfolio/billboard-uksw.jpg", alt: "Billboard UKSW", caption: "Billboard UKSW" },
  { src: "/portfolio/spanduk-pelkatpa.jpg", alt: "Spanduk Pelkat PA", caption: "Spanduk Pelkat PA" },
  { src: "/portfolio/campaign.jpg", alt: "Campaign Design", caption: "Campaign Design" },
];

export const liveStreamItems: GalleryItem[] = [
  { src: "/portfolio/live-anya.mp4", alt: "Anya Zona Layer", caption: "Anya Zona Layer Live Stream Design", isVideo: true },
  { src: "/portfolio/live-ez.mp4", alt: "EZ Squad", caption: "EZ Squad Live Stream Design", isVideo: true },
  { src: "/portfolio/live-raka.mp4", alt: "Raka Trabas", caption: "Raka Trabas Live Stream Design", isVideo: true },
  { src: "/portfolio/live-reno.mp4", alt: "Sinyal Ordal", caption: "Sinyal Ordal Live Stream Design", isVideo: true },
];

export const liveProfiles = [
  { title: "Anya Zona Layer", username: "anyazonalayer", avatarImage: "/portfolio/anya.jpg", avatarText: "A", avatarBg: "from-pink-400 to-rose-500" },
  { title: "EZ Squad", username: "ezsquad", avatarImage: "/portfolio/ez.jpg", avatarText: "EZ", avatarBg: "from-purple-400 to-violet-600" },
  { title: "Raka Trabas", username: "rekatkobra", avatarImage: "/portfolio/raka.jpg", avatarText: "RT", avatarBg: "from-orange-400 to-red-500" },
  { title: "Sinyal Ordal", username: "sinyalord", avatarImage: "/portfolio/sinyalordal.jpg", avatarText: "SO", avatarBg: "from-blue-400 to-cyan-500" },
];

export const defaultThumbnailGrid: GalleryItem[] = Array.from({ length: 9 }, (_, index) => {
  const num = index + 1;
  return {
    src: `/portfolio/thumbnail-${num}.jpg`,
    alt: `Thumbnail ${num}`,
    caption: `Thumbnail ${num}`,
  };
});

export const socialSections: SectionData[] = [
  {
    title: "Pelkat PA GPIB Immanuel Pekanbaru",
    username: "pelkatpa.pku",
    bio: "Ruang ceria anak-anak kreatif & penuh kasih Tuhan 🙏✨ GPIB Immanuel Pekanbaru.",
    avatarImage: "/portfolio/pa-logo.jpg",
    avatarText: "P",
    avatarBg: "from-blue-500 to-indigo-400",
    posts: [
      { src: "/portfolio/pa-1.png", alt: "Pelkat PA 1", caption: "Pelkat PA 1" },
      { src: "/portfolio/pa-2.jpg", alt: "Pelkat PA 2", caption: "Pelkat PA 2" },
      { src: "/portfolio/pa-3.jpg", alt: "Pelkat PA 3", caption: "Pelkat PA 3" },
      { src: "/portfolio/pa-4.jpg", alt: "Pelkat PA 4", caption: "Pelkat PA 4" },
      { src: "/portfolio/pa-5.jpg", alt: "Pelkat PA 5", caption: "Pelkat PA 5" },
      { src: "/portfolio/pa-6.jpg", alt: "Pelkat PA 6", caption: "Pelkat PA 6" },
    ],
    details: {
      client: "GPIB Immanuel Pekanbaru",
      industry: "Community & Ministry",
      role: "Lead Visual Designer",
      year: "2024",
      deliverables: "Event Assets, Story Templates",
      tools: "Photoshop, Illustrator",
    },
    overview: "Joyful and vibrant creative feeds tailored for children's ministry events and daily spiritual content.",
    challenge: "Balancing a warm, playful aesthetic with clean church branding guidelines.",
  },
  {
    title: "UKSW",
    username: "uksw_salatiga",
    bio: "Official visual feed for UKSW Salatiga 🎓 Shaping futures through creative campus stories.",
    avatarImage: "/portfolio/uksw-logo.jpg",
    avatarText: "U",
    avatarBg: "from-pink-500 to-rose-400",
    posts: [
      { src: "/portfolio/uksw-1.jpg", alt: "UKSW Mendunia", caption: "UKSW Mendunia" },
      {
        src: "/portfolio/uksw-2.jpg",
        alt: "Kampus Tour",
        caption: "Kampus Tour",
        subSlides: [
          { src: "/portfolio/uksw-2.jpg", alt: "uksw-2", caption: "uksw-2" },
          { src: "/portfolio/uksw-2a.jpg", alt: "uksw-2a", caption: "uksw-2a" },
          { src: "/portfolio/uksw-2b.jpg", alt: "uksw-2b", caption: "uksw-2b" },
          { src: "/portfolio/uksw-2c.jpg", alt: "uksw-2c", caption: "uksw-2c" },
        ],
      },
      { src: "/portfolio/uksw-3.jpg", alt: "PMB 2026", caption: "PMB 2026" },
      { src: "/portfolio/uksw-4.jpg", alt: "Akreditasi Unggul", caption: "Akreditasi Unggul" },
      { src: "/portfolio/uksw-5.jpg", alt: "UKSW Menyapa", caption: "UKSW Menyapa" },
      { src: "/portfolio/uksw-6.jpg", alt: "Creative Minority", caption: "Creative Minority" },
      {
        src: "/portfolio/uksw-7.jpg",
        alt: "Campus Life",
        caption: "Campus Life",
        subSlides: [
          { src: "/portfolio/uksw-7.jpg", alt: "uksw-7", caption: "uksw-7" },
          { src: "/portfolio/uksw-7a.jpg", alt: "uksw-7a", caption: "uksw-7a" },
          { src: "/portfolio/uksw-7b.jpg", alt: "uksw-7b", caption: "uksw-7b" },
          { src: "/portfolio/uksw-7c.jpg", alt: "uksw-7c", caption: "uksw-7c" },
        ],
      },
      { src: "/portfolio/uksw-8.jpg", alt: "Research & Innovation", caption: "Research & Innovation" },
      { src: "/portfolio/uksw-9.jpg", alt: "Graduation Moment", caption: "Graduation Moment" },
    ],
    details: {
      client: "UKSW Salatiga",
      industry: "Education",
      role: "Lead Visual Designer",
      year: "2024",
      deliverables: "Social Templates, Feed Systems",
      tools: "Figma, Photoshop",
    },
    overview: "Editorial social media systems designed to look refined, coherent, and premium across campus touchpoints.",
    challenge: "Maintaining brand consistency across academic campaigns while keeping designs engaging for students.",
  },
  {
    title: "Jendela Finansial",
    username: "jendelafinansial",
    bio: "Smart financial tips & wealth education made simple 💡 Grow your future with us.",
    avatarImage: "/portfolio/jendela-finansial-logo.jpg",
    avatarText: "JF",
    avatarBg: "from-emerald-500 to-teal-400",
    posts: [
      {
        src: "/portfolio/jendela-1.jpg",
        alt: "jendela-1",
        caption: "jendela-1",
        subSlides: [
          { src: "/portfolio/jendela-1.jpg", alt: "jendela-1", caption: "jendela-1" },
          { src: "/portfolio/jendela-1a.jpg", alt: "jendela-1a", caption: "jendela-1a" },
          { src: "/portfolio/jendela-1b.jpg", alt: "jendela-1b", caption: "jendela-1b" },
          { src: "/portfolio/jendela-1c.jpg", alt: "jendela-1c", caption: "jendela-1c" },
          { src: "/portfolio/jendela-1d.jpg", alt: "jendela-1d", caption: "jendela-1d" },
          { src: "/portfolio/jendela-1e.jpg", alt: "jendela-1e", caption: "jendela-1e" },
        ],
      },
      {
        src: "/portfolio/jendela-2.jpg",
        alt: "jendela-2",
        caption: "jendela-2",
        subSlides: [
          { src: "/portfolio/jendela-2.jpg", alt: "jendela-2", caption: "jendela-2" },
          { src: "/portfolio/jendela-2a.jpg", alt: "jendela-2a", caption: "jendela-2a" },
          { src: "/portfolio/jendela-2b.jpg", alt: "jendela-2b", caption: "jendela-2b" },
          { src: "/portfolio/jendela-2c.jpg", alt: "jendela-2c", caption: "jendela-2c" },
          { src: "/portfolio/jendela-2d.jpg", alt: "jendela-2d", caption: "jendela-2d" },
        ],
      },
      {
        src: "/portfolio/jendela-3.jpg",
        alt: "jendela-3",
        caption: "jendela-3",
        subSlides: [
          { src: "/portfolio/jendela-3.jpg", alt: "jendela-3", caption: "jendela-3" },
          { src: "/portfolio/jendela-3a.jpg", alt: "jendela-3a", caption: "jendela-3a" },
          { src: "/portfolio/jendela-3b.jpg", alt: "jendela-3b", caption: "jendela-3b" },
          { src: "/portfolio/jendela-3c.jpg", alt: "jendela-3c", caption: "jendela-3c" },
          { src: "/portfolio/jendela-3d.jpg", alt: "jendela-3d", caption: "jendela-3d" },
          { src: "/portfolio/jendela-3e.jpg", alt: "jendela-3e", caption: "jendela-3e" },
        ],
      },
      {
        src: "/portfolio/jendela-4.jpg",
        alt: "jendela-4",
        caption: "jendela-4",
        subSlides: [
          { src: "/portfolio/jendela-4.jpg", alt: "jendela-4", caption: "jendela-4" },
          { src: "/portfolio/jendela-4a.jpg", alt: "jendela-4a", caption: "jendela-4a" },
          { src: "/portfolio/jendela-4b.jpg", alt: "jendela-4b", caption: "jendela-4b" },
          { src: "/portfolio/jendela-4c.jpg", alt: "jendela-4c", caption: "jendela-4c" },
          { src: "/portfolio/jendela-4d.jpg", alt: "jendela-4d", caption: "jendela-4d" },
          { src: "/portfolio/jendela-4e.jpg", alt: "jendela-4e", caption: "jendela-4e" },
          { src: "/portfolio/jendela-4f.jpg", alt: "jendela-4f", caption: "jendela-4f" },
          { src: "/portfolio/jendela-4g.jpg", alt: "jendela-4g", caption: "jendela-4g" },
          { src: "/portfolio/jendela-4h.jpg", alt: "jendela-4h", caption: "jendela-4h" },
        ],
      },
      { src: "/portfolio/jendela-5.jpg", alt: "jendela-5", caption: "jendela-5" },
      {
        src: "/portfolio/jendela-6.jpg",
        alt: "jendela-6",
        caption: "jendela-6",
        subSlides: [
          { src: "/portfolio/jendela-6.jpg", alt: "jendela-6", caption: "jendela-6" },
          { src: "/portfolio/jendela-6a.jpg", alt: "jendela-6a", caption: "jendela-6a" },
          { src: "/portfolio/jendela-6b.jpg", alt: "jendela-6b", caption: "jendela-6b" },
          { src: "/portfolio/jendela-6c.jpg", alt: "jendela-6c", caption: "jendela-6c" },
          { src: "/portfolio/jendela-6d.jpg", alt: "jendela-6d", caption: "jendela-6d" },
          { src: "/portfolio/jendela-6e.jpg", alt: "jendela-6e", caption: "jendela-6e" },
          { src: "/portfolio/jendela-6f.jpg", alt: "jendela-6f", caption: "jendela-6f" },
        ],
      },
    ],
    details: {
      client: "Jendela Finansial",
      industry: "Financial Education",
      role: "Lead Visual Designer",
      year: "2024",
      deliverables: "Infographics, Carousels",
      tools: "Figma, Illustrator",
    },
    overview: "Simplifying complex financial insights into clean, engaging, and easy-to-digest visual carousels.",
    challenge: "Translating heavy data and financial terms into highly appealing visuals for young adults.",
  },
  {
    title: "Consistrade",
    username: "consistrade",
    bio: "Professional corporate and trading brand identity design 📈 Global trade made seamless.",
    avatarImage: "/portfolio/consistrade-logo.png",
    avatarText: "C",
    avatarBg: "from-purple-500 to-pink-500",
    posts: [
      { src: "/portfolio/consistrade-1.png", alt: "consistrade-1", caption: "consistrade-1" },
      { src: "/portfolio/consistrade-2.png", alt: "consistrade-2", caption: "consistrade-2" },
      { src: "/portfolio/consistrade-3.png", alt: "consistrade-3", caption: "consistrade-3" },
      { src: "/portfolio/consistrade-4.png", alt: "consistrade-4", caption: "consistrade-4" },
      { src: "/portfolio/consistrade-5.png", alt: "consistrade-5", caption: "consistrade-5" },
      { src: "/portfolio/consistrade-6.png", alt: "consistrade-6", caption: "consistrade-6" },
      { src: "/portfolio/consistrade-7.png", alt: "consistrade-7", caption: "consistrade-7" },
      { src: "/portfolio/consistrade-8.png", alt: "consistrade-8", caption: "consistrade-8" },
      { src: "/portfolio/consistrade-9.png", alt: "consistrade-9", caption: "consistrade-9" },
    ],
    details: {
      client: "Consistrade",
      industry: "Corporate & Trading",
      role: "Lead Visual Designer",
      year: "2024",
      deliverables: "Social Systems, Post Templates",
      tools: "Photoshop, Illustrator",
    },
    overview: "Sleek, authoritative, and modern social media systems designed for global corporate trade.",
    challenge: "Communicating reliability, precision, and global reach through structured financial and trade layouts.",
  },
];

export const brandSections: SectionData[] = [
  {
    title: "Jendela Finansial",
    username: "jendelafinansial",
    bio: "Smart financial tips & wealth education brand identity 💡",
    avatarImage: "/portfolio/jendela-finansial.jpg",
    avatarText: "JF",
    avatarBg: "from-emerald-500 to-teal-400",
    posts: [{ src: "/portfolio/jendela-finansial.jpg", alt: "Jendela Finansial Logo", caption: "Jendela Finansial Logo" }],
    details: {
      client: "Jendela Finansial",
      industry: "Financial Education",
      role: "Lead Brand Designer",
      year: "2024",
      deliverables: "Brand Identity, Logo Suite",
      tools: "Illustrator, Figma",
    },
    overview: "Creating a trustworthy and approachable brand identity for financial education.",
    challenge: "Balancing professional financial trust with friendly, youthful appeal.",
  },
  {
    title: "Pelkat PA GPIB Immanuel Pekanbaru",
    username: "gpib_immanuel_pku",
    bio: "Official church branding and visual identity system 🙏🕊️",
    avatarImage: "/portfolio/pelkatpa.jpg",
    avatarText: "G",
    avatarBg: "from-amber-500 to-orange-400",
    posts: [{ src: "/portfolio/pelkatpa.jpg", alt: "GPIB Immanuel Pekanbaru", caption: "GPIB Immanuel Pekanbaru" }],
    details: {
      client: "GPIB Immanuel Pekanbaru",
      industry: "Religious Organization",
      role: "Lead Brand Designer",
      year: "2024",
      deliverables: "Visual Identity, Stationery",
      tools: "Illustrator, Figma",
    },
    overview: "Establishing a dignified and welcoming brand presence for the congregation.",
    challenge: "Reflecting traditional ecclesiastical values through modern, clean graphic standards.",
  },
  {
    title: "GPIB Immanuel Pekanbaru",
    username: "gpibimmanuelpku",
    bio: "Official church branding and visual identity system 🙏🕊️",
    avatarImage: "/portfolio/gpib-sinode.jpg",
    avatarText: "G",
    avatarBg: "from-amber-500 to-orange-400",
    posts: [{ src: "/portfolio/gpib-thumb.jpg", alt: "GPIB Immanuel Pekanbaru", caption: "GPIB Immanuel Pekanbaru" }],
    details: {
      client: "GPIB Immanuel Pekanbaru",
      industry: "Religious Organization",
      role: "Lead Brand Designer",
      year: "2024",
      deliverables: "Visual Identity, Stationery",
      tools: "Illustrator, Figma",
    },
    overview: "Establishing a dignified and welcoming brand presence for the congregation.",
    challenge: "Reflecting traditional ecclesiastical values through modern, clean graphic standards.",
  },
  {
    title: "Consistrade",
    username: "consistrade",
    bio: "Professional corporate and trading brand identity design 📈",
    avatarImage: "/portfolio/consistrade-thumb.jpg",
    avatarText: "C",
    avatarBg: "from-purple-500 to-pink-500",
    posts: [{ src: "/portfolio/consistrade-thumb.jpg", alt: "Consistrade", caption: "Consistrade" }],
    details: {
      client: "Consistrade",
      industry: "Corporate & Trading",
      role: "Lead Brand Designer",
      year: "2024",
      deliverables: "Corporate Identity, Logo Suite",
      tools: "Illustrator, Photoshop",
    },
    overview: "Crafting a sleek, authoritative, and modern brand identity for global trade.",
    challenge: "Communicating reliability, precision, and global reach through minimal branding.",
  },
  {
    title: "HUT 63 Pelkat PA GPIB",
    username: "pelkatpa.pku",
    bio: "Winning logo design for the 63rd Anniversary of Pelkat PA GPIB 🏆",
    avatarImage: "/portfolio/hut63.jpg",
    avatarText: "PA",
    avatarBg: "from-rose-500 to-pink-500",
    posts: [{ src: "/portfolio/hut63.jpg", alt: "PA Logo HUT 63", caption: "PA Logo HUT 63" }],
    details: {
      client: "Dewan Pelayanan Anak",
      industry: "Ministry",
      role: "Graphic Designer",
      year: "2023",
      deliverables: "Logo Competition Entry",
      tools: "Illustrator",
    },
    overview: "Winning design for the 63rd Pelkat PA GPIB Anniversary logo competition.",
    challenge: "Capturing the spirit of 63 years of service within a concise, iconic mark.",
  },
  {
    title: "HUT 67 Pelkat PA GPIB",
    username: "pelkatpa.pku",
    bio: "Official visual identity for the 67th Pelkat PA GPIB Anniversary 🕊️",
    avatarImage: "/portfolio/hut67.jpg",
    avatarText: "PA",
    avatarBg: "from-blue-500 to-indigo-500",
    posts: [{ src: "/portfolio/hut67.jpg", alt: "Logo HUT Pelkat PA ke-67", caption: "Logo HUT Pelkat PA ke-67" }],
    details: {
      client: "Logo HUT Pelkat PA ke-67",
      industry: "Ministry",
      role: "Lead Brand Designer",
      year: "2024",
      deliverables: "Anniversary Logo",
      tools: "Illustrator, Photoshop",
    },
    overview: "Developing a celebratory and meaningful identity for the 67th anniversary.",
    challenge: "Creating a distinct mark that aligns with church branding while signifying longevity.",
  },
  {
    title: "Soleste",
    username: "soleste_official",
    bio: "Elegance and modern lifestyle brand identity design ✨",
    avatarImage: "/portfolio/soleste.jpg",
    avatarText: "S",
    avatarBg: "from-amber-400 to-yellow-600",
    posts: [{ src: "/portfolio/soleste.jpg", alt: "Soleste Brand", caption: "Soleste Brand Identity" }],
    details: {
      client: "Soleste",
      industry: "Lifestyle & Fashion",
      role: "Lead Brand Designer",
      year: "2024",
      deliverables: "Brand Strategy, Visual Identity",
      tools: "Illustrator, Figma",
    },
    overview: "Crafting a refined, luxury-feeling brand identity for modern lifestyle products.",
    challenge: "Encapsulating sophistication and minimalism while keeping the brand warm and accessible.",
  },
];

export const logoSections: SectionData[] = [
  {
    title: "HUT 63 Pelkat PA GPIB",
    username: "pelkatpa.pku",
    bio: "Winning anniversary emblem for Pelkat PA GPIB 🏆",
    avatarImage: "/portfolio/hut63.jpg",
    avatarText: "PA",
    avatarBg: "from-rose-500 to-pink-500",
    posts: [{ src: "/portfolio/hut63.jpg", alt: "PA Logo HUT 63", caption: "HUT 63 Pelkat PA Logo" }],
    details: {
      client: "Dewan Pelayanan Anak",
      industry: "Religious & Youth",
      role: "Logo Designer",
      year: "2023",
      deliverables: "Competition Winner Emblem",
      tools: "Illustrator",
    },
    overview: "Celebratory 63rd anniversary logo winning entry capturing faith and joy.",
    challenge: "Merging numeric elements with church motifs into a unified circular mark.",
  },
  {
    title: "HUT 67 Pelkat PA GPIB",
    username: "pelkatpa.pku",
    bio: "Official 67th anniversary visual mark 🕊️",
    avatarImage: "/portfolio/hut67.jpg",
    avatarText: "PA",
    avatarBg: "from-blue-500 to-indigo-500",
    posts: [{ src: "/portfolio/hut67.jpg", alt: "Logo HUT Pelkat PA ke-67", caption: "HUT 67 Pelkat PA Logo" }],
    details: {
      client: "Pelkat PA GPIB",
      industry: "Religious & Youth",
      role: "Logo Designer",
      year: "2024",
      deliverables: "Official Anniversary Logo",
      tools: "Illustrator",
    },
    overview: "Modern anniversary identity commemorating 67 years of service and spiritual growth.",
    challenge: "Creating a fresh visual theme while respecting long-standing organizational identity.",
  },
  {
    title: "GPIB Immanuel Pekanbaru",
    username: "gpib_immanuel_pku",
    bio: "Official church emblem and logo mark 🙏🕊️",
    avatarImage: "/portfolio/gpib.jpg",
    avatarText: "G",
    avatarBg: "from-amber-500 to-orange-400",
    posts: [{ src: "/portfolio/gpib.jpg", alt: "GPIB Immanuel Pekanbaru Logo", caption: "GPIB Immanuel Pekanbaru Logo Design" }],
    details: {
      client: "GPIB Immanuel Pekanbaru",
      industry: "Religious Organization",
      role: "Logo Designer",
      year: "2024",
      deliverables: "Church Logo & Visual Mark",
      tools: "Illustrator",
    },
    overview: "Establishing a dignified and welcoming brand presence for the congregation.",
    challenge: "Reflecting traditional ecclesiastical values through modern, clean graphic standards.",
  },
  {
    title: "Joko Tuo",
    username: "jokotuo_heritage",
    bio: "Traditional heritage & authentic culinary mark 🌿",
    avatarImage: "/portfolio/jokotuo.jpg",
    avatarText: "JT",
    avatarBg: "from-emerald-700 to-green-600",
    posts: [{ src: "/portfolio/jokotuo.jpg", alt: "Joko Tuo Logo", caption: "Joko Tuo Logo Design" }],
    details: {
      client: "Joko Tuo",
      industry: "Culinary & Heritage",
      role: "Logo Designer",
      year: "2024",
      deliverables: "Vintage Monogram & Seal",
      tools: "Illustrator, Photoshop",
    },
    overview: "A rich, heritage-inspired logo mark reflecting authentic cultural recipes and tradition.",
    challenge: "Infusing traditional retro artwork while keeping the logo modern and scalable.",
  },
  {
    title: "Consistrade",
    username: "consistrade",
    bio: "Sleek & authoritative corporate trading mark 📈",
    avatarImage: "/portfolio/consistrade.jpg",
    avatarText: "C",
    avatarBg: "from-indigo-600 to-blue-500",
    posts: [{ src: "/portfolio/consistrade.jpg", alt: "Consistrade Logo", caption: "Consistrade Logo Design" }],
    details: {
      client: "Consistrade",
      industry: "Corporate Trading",
      role: "Logo Designer",
      year: "2024",
      deliverables: "Corporate Emblem & Guidelines",
      tools: "Illustrator",
    },
    overview: "Geometrical and strong trading logo conveying growth, trust, and consistency.",
    challenge: "Integrating abstract arrow and trade symbols without cluttering the silhouette.",
  },
  {
    title: "Minci",
    username: "minci_brand",
    bio: "Playful & friendly mascot-driven brand logo 🐱",
    avatarImage: "/portfolio/minci.jpg",
    avatarText: "M",
    avatarBg: "from-pink-400 to-rose-400",
    posts: [{ src: "/portfolio/minci.jpg", alt: "Minci Logo", caption: "Minci Logo Design" }],
    details: {
      client: "Minci",
      industry: "Consumer Goods",
      role: "Logo Designer",
      year: "2024",
      deliverables: "Character Logo & Packaging Badge",
      tools: "Illustrator",
    },
    overview: "Warm and inviting character-based logo design built for high brand recall.",
    challenge: "Balancing cute mascot elements with scalable graphic typography.",
  },
  {
    title: "Nona Kirana",
    username: "nonakirana",
    bio: "Charming & feminine aesthetic visual identity 🌸",
    avatarImage: "/portfolio/kirana.jpg",
    avatarText: "NK",
    avatarBg: "from-pink-300 to-purple-400",
    posts: [{ src: "/portfolio/kirana.jpg", alt: "Nona Kirana Logo", caption: "Nona Kirana Logo Design" }],
    details: {
      client: "Nona Kirana",
      industry: "Beauty & Beauty Care",
      role: "Logo Designer",
      year: "2024",
      deliverables: "Wordmark & Monogram",
      tools: "Illustrator, Font Self",
    },
    overview: "Elegant typographic and monogram design crafted for personal branding and beauty.",
    challenge: "Designing delicate line work that maintains clarity across small digital icons.",
  },
  {
    title: "Sinyal Ordal",
    username: "sinyalordal",
    bio: "Tech & insider signals community mark 📡",
    avatarImage: "/portfolio/sinyalordal.jpg",
    avatarText: "SO",
    avatarBg: "from-cyan-500 to-blue-600",
    posts: [{ src: "/portfolio/sinyalordal.jpg", alt: "Sinyal Ordal Logo", caption: "Sinyal Ordal Logo Design" }],
    details: {
      client: "Sinyal Ordal",
      industry: "Technology & Community",
      role: "Logo Designer",
      year: "2024",
      deliverables: "Digital Logo Suite",
      tools: "Illustrator, Figma",
    },
    overview: "A sharp, futuristic logo design symbolising signal flow and exclusive networking.",
    challenge: "Crafting an abstract signal icon that feels both tech-forward and trustworthy.",
  },
  {
    title: "Soleste",
    username: "soleste_official",
    bio: "Modern & elegant lifestyle brand mark ✨",
    avatarImage: "/portfolio/soleste.jpg",
    avatarText: "S",
    avatarBg: "from-amber-400 to-yellow-600",
    posts: [{ src: "/portfolio/soleste.jpg", alt: "Soleste Logo", caption: "Soleste Logo Design" }],
    details: {
      client: "Soleste",
      industry: "Lifestyle & Fashion",
      role: "Logo Designer",
      year: "2024",
      deliverables: "Logo Mark, Identity System",
      tools: "Illustrator, Vector",
    },
    overview: "A refined and luxury-feeling brand mark tailored for modern lifestyle products.",
    challenge: "Creating a simple yet memorable emblem that conveys elegance and durability.",
  },
  {
    title: "Pivot Point by Mark Liem",
    username: "pivotpoint_markliem",
    bio: "Executive coaching & strategic consulting logo 🎯",
    avatarImage: "/portfolio/pivot.jpg",
    avatarText: "PP",
    avatarBg: "from-slate-700 to-zinc-900",
    posts: [{ src: "/portfolio/pivot.jpg", alt: "Pivot Point Logo", caption: "Pivot Point Logo Design" }],
    details: {
      client: "Mark Liem",
      industry: "Consulting & Executive Coaching",
      role: "Logo Designer",
      year: "2024",
      deliverables: "Personal Branding Logo",
      tools: "Illustrator, Figma",
    },
    overview: "Minimalist monogram emblem designed for high-level personal executive branding.",
    challenge: "Distilling strategic transformation and direction into a sleek geometric monogram.",
  },
  {
    title: "Raka Trabas",
    username: "rakatrabas",
    bio: "Dynamic & energetic adventure community logo 🚵‍♂️",
    avatarImage: "/portfolio/raka.jpg",
    avatarText: "RT",
    avatarBg: "from-orange-500 to-red-500",
    posts: [{ src: "/portfolio/raka.jpg", alt: "Raka Trabas Logo", caption: "Raka Trabas Logo Design" }],
    details: {
      client: "Raka Trabas",
      industry: "Outdoor & Sports",
      role: "Logo Designer",
      year: "2024",
      deliverables: "Community Logo, Apparel Badge",
      tools: "Illustrator, Photoshop",
    },
    overview: "Bold and high-energy logo mark created for off-road & adventure sports enthusiasts.",
    challenge: "Blending ruggedness with clean, modern vector lines for print on merchandise.",
  },
];